# $FreeBSD: releng/9.3/usr.sbin/bsdinstall/scripts/Makefile 264437 2014-04-14 01:18:02Z dteske $

SCRIPTS= auto adduser checksum config docsinstall entropy hostname jail \
	 keymap mirrorselect mount netconfig netconfig_ipv4 netconfig_ipv6 \
	 rootpass script services time umount wlanconfig zfsboot
BINDIR= /usr/libexec/bsdinstall

NO_MAN=	true

.include <bsd.prog.mk>
