# $FreeBSD: releng/9.3/tools/tools/cxgbetool/Makefile 265589 2014-05-07 19:13:09Z np $

PROG=	cxgbetool
SRCS=	cxgbetool.c
NO_MAN=
CFLAGS+= -I${.CURDIR}/../../../sys/dev/cxgbe -I${.CURDIR}/../../../sys -I.
BINDIR?= /usr/sbin

.include <bsd.prog.mk>
