# $FreeBSD: releng/9.3/lib/clang/libllvmvectorize/Makefile 263509 2014-03-21 17:56:32Z dim $

.include <bsd.own.mk>

LIB=	llvmvectorize

SRCDIR=	lib/Transforms/Vectorize
SRCS=	BBVectorize.cpp \
	LoopVectorize.cpp \
	SLPVectorizer.cpp \
	Vectorize.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
