# $FreeBSD: releng/9.3/usr.sbin/bsdconfig/usermgmt/share/Makefile 263791 2014-03-27 03:20:47Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/bsdconfig/usermgmt
FILES=		group.subr group_input.subr user.subr user_input.subr

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
