# $FreeBSD: releng/9.3/lib/clang/libllvmexecutionengine/Makefile 263509 2014-03-21 17:56:32Z dim $

.include <bsd.own.mk>

LIB=	llvmexecutionengine

SRCDIR=	lib/ExecutionEngine
SRCS=	ExecutionEngine.cpp \
	ExecutionEngineBindings.cpp \
	RTDyldMemoryManager.cpp \
	TargetSelect.cpp

.include "../clang.lib.mk"
