# $FreeBSD: releng/9.3/usr.sbin/bsdconfig/examples/Makefile 255991 2013-10-02 16:32:07Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/examples/bsdconfig
FILES=		browse_packages_ftp.sh browse_packages_http.sh bsdconfigrc

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
