# $FreeBSD: releng/9.3/usr.bin/clang/llvm-nm/Makefile 263509 2014-03-21 17:56:32Z dim $

.include <bsd.own.mk>

PROG_CXX=llvm-nm

SRCDIR=	tools/llvm-nm
SRCS=	llvm-nm.cpp

LIBDEPS=llvmobject \
	llvmbitreader \
	llvmcore \
	llvmsupport

.include "../clang.prog.mk"
